First and second hw
vitaliimak/FE_Course pull request #1
Opened 2022-03-26 12:31 UTC by amigo228

1 and 2 homeworks

2022-03-27 19:25 UTC, vitaliimak requested changes
По першому ДЗ, добре, що зроблено 2 варінти резюме для різних мов.
Для другого ДЗ не вистачає використання якорів https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#linking_to_an_element_on_the_same_page і картинок (їх можна взяти наприклад тут https://www.freepik.com/)

2022-03-27 19:25 UTC, vitaliimak commented on src/rudiy_rostyslav/02/index.html
> +            <article>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum impedit atque consequatur esse
Це скоріше тільки параграф, а не повноцінна стаття.

2022-03-27 19:25 UTC, vitaliimak commented on src/rudiy_rostyslav/02/index.html
> +        <form>
У форми має бути можливість зберегти введені дані, а саме кнопка на яку зможе натиснути користувач.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form

2022-03-27 19:25 UTC, vitaliimak commented on src/rudiy_rostyslav/02/index.html
> +                <input type="password" name="password" id="password">
Відсутній `placeholder`

2022-03-27 19:25 UTC, vitaliimak commented on src/rudiy_rostyslav/02/index.html
> +        <iframe src="/FE_Course/src/rudiy_rostyslav/01/1en.html"></iframe>
`iframe` повинен містити `title` атрибут
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#accessibility_concerns

2022-03-27 19:25 UTC, vitaliimak commented on src/rudiy_rostyslav/02/index.html
> +                <label for="name">Ім'я</label>
Вся сторінка на англійській але елементи форми на український, якщо це потрібно, то варто вказати `lang="uk"` для форми, або зробити все на одній мові.

2022-03-28 11:16 UTC, amigo228 commented on src/rudiy_rostyslav/02/index.html
> +
Добре,зрозумів)

2022-03-30 08:31 UTC, amigo228 commented on src/rudiy_rostyslav/02/index.html
> +    <link href="/FE_Course/src/rudiy_rostyslav/02/style.css" rel="stylesheet" type="text/css">
Пофіксив запуск лайв сервера.
Була проблема з каталогами і шляхами

2022-03-30 08:31 UTC, amigo228 commented on src/rudiy_rostyslav/02/index.html
> +        <section>
ок

2022-03-30 08:32 UTC, amigo228 commented on src/rudiy_rostyslav/02/index.html
> +            <article>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rerum impedit atque consequatur esse
+

2022-03-30 08:32 UTC, amigo228 commented on src/rudiy_rostyslav/02/index.html
> +        <form>
Ну я думаю що тут було це неважливо , але в цілому так

2022-03-30 08:32 UTC, amigo228 commented on src/rudiy_rostyslav/02/index.html
> +                <label for="name">Ім'я</label>
ок

2022-03-30 08:33 UTC, amigo228 commented on src/rudiy_rostyslav/02/index.html
> +                <input type="password" name="password" id="password">
ок

2022-03-30 08:38 UTC, amigo228 commented on src/rudiy_rostyslav/01/1.html
> +<html lang="en">
ok

2022-03-30 08:39 UTC, amigo228 commented on src/rudiy_rostyslav/01/1.html
> +    <h4>Соціальні мережі</h4>
ok

2022-03-30 08:39 UTC, amigo228 commented on src/rudiy_rostyslav/01/1.html
> +        <li> <a href="https://www.instagram.com/rost__rr/" target="_blank"> Instagram</a></li>
ok

2022-03-30 08:39 UTC, amigo228 commented on src/rudiy_rostyslav/01/1.html
> +</html>
ok

2022-03-30 19:35 UTC, vitaliimak commented on src/rudiy_rostyslav/02/index.html
> +        <form>
А яка ціль використовувати тут форму без кнопки?

2022-03-31 08:52 UTC, amigo228 commented on src/rudiy_rostyslav/02/index.html
> +        <form>
Ну в данному випадку, немає цілі використовувати кнопку

2022-04-02 15:19 UTC, vitaliimak approved these changes

2022-04-02 15:19 UTC, vitaliimak commented on src/rudiy_rostyslav/02/index.html
> +                    <a href="" class="nav-link">Home</a>
Завжди варто проставляти лінку. Як плейсхолдер можна поставити `#` якщо лінка невідома.

2022-04-02 16:19 UTC, merged