06 homework hrytsiak yaroslav
vitaliimak/FE_Course pull request #15
Opened 2022-04-01 11:13 UTC by YAroslav9405

2022-04-03 10:14 UTC, vitaliimak requested changes
Чудо, що є чітко вирежена структура документу. Поділ на секції.
На макеті є 10 svg картинки, і 4 - jpg. Має бути експортовано 14 картинок з такими форматами.
Крім того є ще 4 картинки, які не використовуються на самій сторінці але є на макеті.

2022-04-03 10:14 UTC, vitaliimak commented on src/yaroslav_hrytsiak/06/index.html
> +                     </table>
Таблиці використовуємо тільки для відображення табличних даних. Тут варто використати список з лінками на якоря.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#linking_to_an_element_on_the_same_page

2022-04-03 10:14 UTC, vitaliimak commented on src/yaroslav_hrytsiak/06/index.html
> +               <img src="image/pofile_photo.png" alt="Profile_photo" title="Profile_photo" class="photo">
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#the_title_attribute

2022-04-03 10:14 UTC, vitaliimak commented on src/yaroslav_hrytsiak/06/index.html
> +                    <img src="image/figma.png" alt="Figma" title="Figma" class="figma">
Там де є перечислення елементів одного типу зважди варто використати список.

2022-04-03 10:14 UTC, vitaliimak commented on src/yaroslav_hrytsiak/06/index.html
> +                    <h3 class="about">About me</h3>
Заголовки йдуть по порядку.

2022-04-03 10:14 UTC, vitaliimak commented on src/yaroslav_hrytsiak/06/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&display=swap" rel="stylesheet">
Вірно виявлений основний шрифт, але на макеті є ще один.

2022-04-04 10:31 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/06/package.json
> +{
А якщо їх помістити в gitignore , так можна ?

2022-04-04 12:50 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/01/styles/styles.css
> +    box-shadow: rgb(0 0 0 / 0.1) 6px 6px 20px;
Done

2022-04-04 12:50 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/06/package.json
> +{
Done

2022-04-04 12:51 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/06/index.html
> +                     </table>
Done

2022-04-04 12:51 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/06/index.html
> +               <img src="image/pofile_photo.png" alt="Profile_photo" title="Profile_photo" class="photo">
Done

2022-04-04 12:51 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/06/index.html
> +                    <img src="image/figma.png" alt="Figma" title="Figma" class="figma">
Done

2022-04-04 12:51 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/06/index.html
> +                    <h3 class="about">About me</h3>
Done

2022-04-04 12:51 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/06/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;500&display=swap" rel="stylesheet">
Done

2022-04-05 12:34 UTC, vitaliimak approved these changes

2022-04-05 12:38 UTC, merged