Added my second homework without using a fork
vitaliimak/FE_Course pull request #16
Opened 2022-04-01 11:18 UTC by SchokinViktor

2022-04-02 16:28 UTC, vitaliimak requested changes
Частину коментарів з закритих ПР-ів виправлено, але деякі проблеми все ще підсвічуються лінтером.

2022-04-02 16:28 UTC, vitaliimak commented on src/viktor_shchokin/02/index.html
> +        <section>
Інші `section` з заголовком, а цей без.

2022-04-02 16:28 UTC, vitaliimak commented on src/viktor_shchokin/02/index.html
> +            <img class="img" src="img/3.png" alt="img3">
`alt` атрибути варто робити в людиночитаємому форматі.
https://github.com/vitaliimak/FE_Course/pull/2#discussion_r835957514

2022-04-02 17:58 UTC, SchokinViktor commented on src/viktor_shchokin/02/index.html
> +        <section>
done

2022-04-02 17:58 UTC, SchokinViktor commented on src/viktor_shchokin/02/index.html
> +            <img class="img" src="img/3.png" alt="img3">
done

2022-04-03 08:45 UTC, vitaliimak approved these changes

2022-04-03 08:58 UTC, merged