solutions for 1st and 2nd homework
vitaliimak/FE_Course pull request #2
Opened 2022-03-26 12:38 UTC by Sergey-Ananiev

2022-03-27 20:37 UTC, vitaliimak requested changes
Хороша ідея з використанням якісних власних скріншотів з кодом.
Варто уважніше писати теги, щоб не виникало ситуації з незакритими або зайвими пустими тегами.

2022-03-27 20:37 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +                <input id="chrome" type="checkbox" name="browsers" checked>Chrome
Для цілі показати, що браузер підтримує технологію не варто використовувати `input` так як користувач може легко зняти галочку.

2022-03-27 20:37 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +            <label for="chrome">
В даному випадку атрибут `for` не обов'язковий, так як `input` дочірній елемент лейбла.

2022-03-27 20:37 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +                <input id="firefox" type="checkbox" name="browsers" checked>Firefox
В межах форми варто використовувати унікальний атрибут `name`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-name
В даному випадку `input` не потрібно використовувати взагалі.

2022-03-27 20:37 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +            <img src="./img/section_tag.png" alt="section_tag">
В `alt` атрибуті повинен бути людино читаємий текст, який допоможе користувачам зрозуміти, що на картинці.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img

2022-03-27 20:37 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +        </section>
Зайвий закриваючий тег, відкриваючого немає.

2022-03-27 20:37 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +        <article>
Тут все ще варто продовжувати використовувати `section`

2022-03-27 20:37 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +                title="YouTube video player" frameborder="0"
Якщо елемент Deprecated це значить, що він вже не підтримується і буде скоріше за все видалений з наступних версій стандарту. Такі елементи не варто використовувати.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-frameborder

2022-03-27 20:37 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +            <iframe src="/HM_1/CV_Eng/index.html" frameborder="0" width="560" height="315"></iframe>
`iframe` повинен містити `title` атрибут
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#accessibility_concerns

2022-03-27 20:37 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +            <iframe src="/HM_1/CV_Eng/index.html" frameborder="0" width="560" height="315"></iframe>
`iframe` також не відображається так як шлях не правильний
![Uploading 2022-03-27_23-31.png…]()

2022-03-27 20:37 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +    <footer>2022 Beetroot
Контент в середині `footer` варто покласти в `<p>` тег.

2022-03-28 16:33 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +            <iframe src="/HM_1/CV_Eng/index.html" frameborder="0" width="560" height="315"></iframe>
Не залився скріншот на GitHub :(
![2022-03-27_23-31](https://user-images.githubusercontent.com/6152066/160444998-248f864c-951f-4bec-a801-13ff4b9c5050.png)

2022-03-28 16:35 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +            <iframe src="/HM_1/CV_Eng/index.html" frameborder="0" width="560" height="315"></iframe>
Там абсолютний шлях і папки HM_1/ немає

2022-03-28 16:40 UTC, Sergey-Ananiev commented on src/sergey_ananiev/01/index.html
> +    <h1 style="text-align: center;">Sergey Ananiev</h1>
done

2022-03-28 16:40 UTC, Sergey-Ananiev commented on src/sergey_ananiev/01/index.html
> +    <h2 style="text-align: center;">Personal:<h2/>
done

2022-03-28 16:40 UTC, Sergey-Ananiev commented on src/sergey_ananiev/01/index.html
> +    <p>- Master's degree in Computer Science</p>
done

2022-03-28 16:40 UTC, Sergey-Ananiev commented on src/sergey_ananiev/01/index.html
> +    <P>- Android Systems Architecture</P>
done

2022-03-28 16:41 UTC, Sergey-Ananiev commented on src/sergey_ananiev/01/index.html
> +</html>
done 
(thanks for the article!)

2022-03-28 16:55 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +            <a href="#section-3-section-element">HTML5 &ltsection&gt елемент</a>
done

2022-03-28 16:55 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +            <a href="#section-6-footer-element">HTML5 &ltfooter&gt елемент</a>
done

2022-03-28 16:57 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +            <p>Приклади <b>не семантичних</b> елементів: &ltdiv&gt і &ltspan&gt- нічого не говорить
done

2022-03-28 16:59 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +            <label for="chrome">
но я читал, что считается хорошей практикой задавать элементу Label атрибут for со значением = значению ID его инпута.

Это критично? Я сделаю ресерч на эту тему.

2022-03-28 17:07 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +            <label for="chrome">
Согласно этому топику, я так понимаю, это не является ошибкой, а больше используется для каждого разработчика, в зависимости от его удобства - 
https://stackoverflow.com/questions/36334658/label-for-and-input-id

2022-03-28 17:07 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +            <label for="chrome">
Не критично, твоя реалізація також вірна.
А розібратися детальніше це класна ідея!

2022-03-28 17:28 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +                <input id="chrome" type="checkbox" name="browsers" checked>Chrome
Преобразовано в горизонтальный список

2022-03-28 17:28 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +                <input id="firefox" type="checkbox" name="browsers" checked>Firefox
Преобразовано в горизонтальный список

2022-03-28 17:32 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +            <img src="./img/section_tag.png" alt="section_tag">
Переименовал, но не уверен, что до конца понял. 
Или нужно ввести в alt прямо код html, который на картинке?

2022-03-28 17:36 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +        <article>
Окей, исправлено.

Но скажите, разве это уже не отдельная часть контента страницы? Мне казалось, что она не продолжает общую идею из main, и поэтому я ставил тут article.

2022-03-28 17:38 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +                title="YouTube video player" frameborder="0"
done

2022-03-28 17:39 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +    <footer>2022 Beetroot
done

2022-03-28 17:42 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +            <iframe src="/HM_1/CV_Eng/index.html" frameborder="0" width="560" height="315"></iframe>
done

2022-03-28 17:42 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +        </section>
done

2022-03-29 13:44 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +            <img src="./img/section_tag.png" alt="section_tag">
> The alt attribute holds a text description of the image, which isn't mandatory but is incredibly useful for accessibility — screen readers read this description out to their users so they know what the image means. Alt text is also displayed on the page if the image can't be loaded for some reason: for example, network errors, content blocking, or linkrot.

Цей атрибут допоможе користувачам які з тих чи інших причин не отримали зображення (повільний інтернет, проблеми з зором, тощо) зрозуміти, що на зображенні. 
Наприклад якщо на картинці пейзаж, то в `alt` може бути написано - Пейзаж

2022-03-29 13:50 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +        <article>
В документі по якому версталася ця домашка гарне визначення тегу. Якщо контент з цього тегу можна взяти окремо від всієї іншої сторінки, то це `article` якщо ні то ні.
Для цього контенту плюс мінус це можна сказати. Але я би сказав, що краще цей тег використовувати на дійсно статтях в блозі, чи новинах на сайті, чи чомусь подібному.

2022-03-29 14:29 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +        <article>
Понял. Спасибо!

2022-03-30 20:22 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +            <img src="./img/section_tag.png" alt="section_tag">
В принципі скрін рідер (наприклад цей https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn/related) читає опис нормально, але якщо з картинкою щось станеться і вона не загрузиться то буде виглядати так:
![2022-03-30_23-20](https://user-images.githubusercontent.com/6152066/160924100-ed78db25-36cf-426e-a1e1-6893a8c2e6a8.png)
Не дуже людино читаємо і ще й на англійській, в той час як весь інший контент на українській.

2022-03-30 20:24 UTC, vitaliimak commented on src/sergey_ananiev/02/index.html
> +            <p>У цьому вiдео ви познайомитеся с академiэю Beetroot, а також побачите резюме одного з учнiв:</p>
Отут `p` насправді виступає заголовком секції з відео.

2022-03-30 20:26 UTC, vitaliimak approved these changes
Загалом все супер, тому тільки змерджити останні зміни з main і пофіксити помилки лінтера.

2022-03-31 06:31 UTC, Sergey-Ananiev commented on src/sergey_ananiev/02/index.html
> +            <p>У цьому вiдео ви познайомитеся с академiэю Beetroot, а також побачите резюме одного з учнiв:</p>
Исправлено

2022-03-31 08:31 UTC, vitaliimak approved these changes

2022-03-31 08:32 UTC, merged