Sixth homework rudyi
vitaliimak/FE_Course pull request #21
Opened 2022-04-02 07:02 UTC by amigo228

2022-04-03 11:13 UTC, vitaliimak requested changes
На макеті є 10 svg картинки, і 4 - jpg. Має бути експортовано 14 картинок з такими форматами. 
Для деяких вибрано не вірний формат. Якщо картинка не фото, а малюнок з прозорітю чи без, і на макеті її можна збільшити без втрати якості (без появи видимих пікселів) то це скоріше за все векторна картинка в форматі svg. Якщо це явно фотографія у якої немає прозорості і при збільшенні втрачається якість (видно драбину пікселів по краю якоїсь лінії) то це jpg. Ну і те, що залишилосеея, це вже png.

Потрібно все ще експортувати картинки у відповідних форматах і перевірити їх кількість.
Також тут ти використав іншу назву персональної папки. Перенеси, будь ласка, цю роботу в свою персональну папку яка вже є в `main` гілці і в підпапку 06. Для цього потрібно змерджити зміни з `main` в твою гілку.

2022-04-03 11:13 UTC, vitaliimak commented on src/rudyi_rostyslav/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100&family=Open+Sans:wght@700&display=swap"
На макеті є шрифт Inter? Основний Open Sans вибрано вірно, але там є ще один. 
Я не бачу, щоб на сторінці десь був використаний Inter, тому його потрібно видалити.

2022-04-03 11:13 UTC, vitaliimak commented on src/rudyi_rostyslav/index.html
> +            <a href="#contacts" class="same">Contacts</a>
Супер, що використав якоря. Також для списків схожих елементів, особливо в навігації варто використовувати списки `ul>li*5>a`

2022-04-03 11:13 UTC, vitaliimak commented on src/rudyi_rostyslav/index.html
> +            <h1 class="fb1" id="about">About me</h1>
`h1` тег на сторінці має бути тільки в одному екземплярі.

2022-04-03 11:13 UTC, vitaliimak commented on src/rudyi_rostyslav/index.html
> +        <div class="block1">
Варто використати семантичні `section` для виділення відповідних секцій і підсекцій для секції Portfolio.

2022-04-03 11:13 UTC, vitaliimak commented on src/rudyi_rostyslav/index.html
> +            <img src="images/adobe.png" alt="adobe" title="adobe">
Так як картинки мають бути іншими, то і структура буде іншою. І не забува про списки коли використовуєш кілька схожих елементів (таких як зірочки, наприклад).

2022-04-04 09:08 UTC, amigo228 commented on src/rudyi_rostyslav/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100&family=Open+Sans:wght@700&display=swap"
ok

2022-04-04 09:08 UTC, amigo228 commented on src/rudyi_rostyslav/index.html
> +            <a href="#contacts" class="same">Contacts</a>
+

2022-04-04 09:08 UTC, amigo228 commented on src/rudyi_rostyslav/index.html
> +            <h1 class="fb1" id="about">About me</h1>
ok

2022-04-04 09:08 UTC, amigo228 commented on src/rudyi_rostyslav/index.html
> +        <div class="block1">
ok

2022-04-04 09:08 UTC, amigo228 commented on src/rudyi_rostyslav/index.html
> +            <img src="images/adobe.png" alt="adobe" title="adobe">
ok

2022-04-06 17:53 UTC, vitaliimak commented on src/rudyi_rostyslav/index.html
> +            <a href="#contacts" class="same">Contacts</a>
Тут змін в ПР не має.

2022-04-06 17:57 UTC, vitaliimak approved these changes
Загалом ок, хоча в деяких місцях використані не дуже підходящі теги. Наприклад не використані списки де їх потрібно використовувати.

2022-04-06 19:35 UTC, merged