Add first new home work
vitaliimak/FE_Course pull request #3
Opened 2022-03-26 12:41 UTC by Stivmen

2022-03-28 07:27 UTC, vitaliimak requested changes
Загалом все дуже добре, без синтаксичних помилок і креативно.
Плюс до коментарів в рев'ю, ще потрібно видалити пустий файл стилів. Якщо він не використовується додавати його не потрібно (принцип YAGNI)

2022-03-28 07:27 UTC, vitaliimak commented on src/panasiuk_stanislav/02/Index.html
> +                <li>&lt;section&gt;</li>
Тег `li` має бути завжди вкладений в `ul` або `ol` 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li

2022-03-28 07:27 UTC, vitaliimak commented on src/panasiuk_stanislav/02/Index.html
> +            <figure><img src="/02/IMG/label.png" alt="веб. кліенти"></figure>
Абсолютні шляхи дуже крихка річ
![2022-03-28_10-21](https://user-images.githubusercontent.com/6152066/160346789-0c8d45d2-1bf7-473d-9906-92355e5d03ad.png)

2022-03-28 07:27 UTC, vitaliimak commented on src/panasiuk_stanislav/02/Index.html
> +        <iframe src=/01/index.html frameborder="0" width="1000" height="1000"></iframe><br>
Завжди використовуй подвійні лапки для значень атрибутів.
Також `iframe` повинен містити `title` атрибут
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#accessibility_concerns
А елемент `frameboarder` Deprecated і це значить, що він вже не підтримується і буде скоріше за все видалений з наступних версій стандарту. Такі елементи не варто використовувати.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-frameborder

2022-03-30 20:29 UTC, vitaliimak commented on .editorconfig
> -indent_size = 4
Цей файл зазвичай буду міняти тільки я, тому тут можуть виникнути конфлікти при мерджі змін з main.

2022-03-31 13:43 UTC, Stivmen commented on src/panasiuk_stanislav/02/Index.html
> +<html lang="ru">
Done.

2022-04-01 07:28 UTC, Stivmen commented on src/panasiuk_stanislav/02/Index.html
> +<body>
done

2022-04-01 07:29 UTC, Stivmen commented on src/panasiuk_stanislav/02/Index.html
> +        <section>
done

2022-04-01 07:31 UTC, Stivmen commented on src/panasiuk_stanislav/02/Index.html
> +            <P>Семантичний елемент чітко описує його значення як для браузера, так і
done

2022-04-01 07:31 UTC, Stivmen commented on src/panasiuk_stanislav/01/index.html
> +        <link rel="stylesheet" href="meta.css">
done

2022-04-01 07:34 UTC, Stivmen commented on src/panasiuk_stanislav/02/Index.html
> +            </header>
done

2022-04-01 07:35 UTC, Stivmen commented on src/panasiuk_stanislav/02/Index.html
> +            <figure><img src="/02/IMG/label.png" alt="веб. кліенти"></figure>
done

2022-04-01 07:36 UTC, Stivmen commented on src/panasiuk_stanislav/02/Index.html
> +                <li>&lt;section&gt;</li>
done

2022-04-01 07:36 UTC, Stivmen commented on src/panasiuk_stanislav/02/Index.html
> +        <iframe src=/01/index.html frameborder="0" width="1000" height="1000"></iframe><br>
done

2022-04-01 08:12 UTC, Stivmen commented on src/panasiuk_stanislav/01/index.html
> +</html>
done

2022-04-01 08:12 UTC, Stivmen commented on src/panasiuk_stanislav/01/index.html
> +            <div class="achieving" id="achieving">
done

2022-04-01 08:21 UTC, Stivmen commented on src/panasiuk_stanislav/01/index.html
> +            <article class="conteiner" id="conteiner">
done

2022-04-01 08:27 UTC, Stivmen commented on src/panasiuk_stanislav/01/index.html
> +                </p>
done

2022-04-01 08:29 UTC, Stivmen commented on src/panasiuk_stanislav/01/index.html
> +    </head>
Цей блок <div> використовується тільки для створення друго-го шару для задньго фону.

2022-04-02 07:20 UTC, vitaliimak commented on src/panasiuk_stanislav/01/index.html
> +                </p>
@Stivmen 
Thank you

2022-04-03 13:36 UTC, vitaliimak commented
@Stivmen, онови, будь ласка, ПР. Так як тут було описано тут https://20220222femak-lsk9012.slack.com/archives/C033YE6TE67/p1648921264026079 щоб мати можливість змерджити ПР. Там буде кілька помилок лінтера.
Плюс, я не замітив ранціше, файли `index.html` і `style.css` з великої букви. Для їх коректного перейменування в Windows використай:
https://github.com/vitaliimak/FE_Course/pull/5#pullrequestreview-929200116

2022-04-03 15:06 UTC, Stivmen commented
Вроде всё пофиксил, и обновил!


вс, 3 апр. 2022 г. в 16:37, Vitalii Makarchenkov ***@***.***>:

> @Stivmen <https://github.com/Stivmen>, онови, будь ласка, ПР. Так як тут
> було описано тут
> https://20220222femak-lsk9012.slack.com/archives/C033YE6TE67/p1648921264026079
> щоб мати можливість змерджити ПР. Там буде кілька помилок лінтера.
> Плюс, я не замітив ранціше, файли index.html і style.css з великої букви.
> Для їх коректного перейменування в Windows використай:
> #5 (review)
> <https://github.com/vitaliimak/FE_Course/pull/5#pullrequestreview-929200116>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vitaliimak/FE_Course/pull/3#issuecomment-1086870933>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX4W2FKPI6A2ZWJBGM5FDKDVDGNILANCNFSM5RXANCAQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-03 15:59 UTC, vitaliimak approved these changes

2022-04-03 16:00 UTC, merged

2022-04-03 16:02 UTC, Stivmen commented
выполнил мердж


вс, 3 апр. 2022 г. в 18:59, Vitalii Makarchenkov ***@***.***>:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vitaliimak/FE_Course/pull/3#pullrequestreview-929691795>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AX4W2FMFSIPH3SBLV4U7W3DVDG57ZANCNFSM5RXANCAQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>