Add homework
vitaliimak/FE_Course pull request #5
Opened 2022-03-26 12:41 UTC by YAroslav9405

2022-03-28 15:30 UTC, vitaliimak requested changes
Загалом дуже добре, є тільки кілька не значних запитань.

2022-03-28 15:30 UTC, vitaliimak commented on src/yaroslav_hrytsiak/01/index.html
> +                    <h4 class="work-position">Manager<span class="organization">Roga & Kopyta New</span>  </h4>
Компанія класна, але пропущено пробіл після Manager, тому слова на сторінці зливаються. Також варто використовувати html коди для спеціальних символів таких як `&`. Які використовуються в розмітці і в коді
https://www.toptal.com/designers/htmlarrows/
![2022-03-28_13-30](https://user-images.githubusercontent.com/6152066/160428865-87d0929a-6355-49f3-a3d6-cd8a2481f78e.png)

2022-03-28 15:30 UTC, vitaliimak commented on src/yaroslav_hrytsiak/01/index.html
> +                         <a href="+tel:380966704441" class="contact-link">+38(096) 67 04 44 1</a> </p>
Круто, що використав телефонний лінк! Тільки формат лінка трішки інший, плюс не на самому початку. При тестуванні сторінки можна перевірити, ще цей лінк робить щось не те, що задумано.

2022-03-28 15:30 UTC, vitaliimak commented on src/yaroslav_hrytsiak/01/index.html
> +                          <a href="https://www.facebook.com/jaroslaw.gr" class="contact-link">my profile</a> </p>
Для лінків переводять користувача на інші ресурси (по за межі твого сайту) варто використовувати `target="_blank"`
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target

2022-03-28 15:30 UTC, vitaliimak commented on src/yaroslav_hrytsiak/01/index.html
> +</html>
В кінці кожного файла варто додавати пусту строку
https://stackoverflow.com/questions/2287967/why-is-it-recommended-to-have-empty-line-in-the-end-of-a-source-file

2022-03-28 15:30 UTC, vitaliimak commented on src/yaroslav_hrytsiak/02/index.html
> +                        <iframe src="/src/yaroslav_hrytsiak/01/index.html"></iframe>
`iframe` повинен містити `title` атрибут
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#accessibility_concerns

2022-03-30 21:26 UTC, vitaliimak requested changes
Все ще є кілька зауважень. І також варто змерджити зміни з main щоб побачити помилки лінтера.

2022-03-30 21:26 UTC, vitaliimak commented on src/yaroslav_hrytsiak/01/index.html
> +            </section>
Я би виніс цю секцію в `header`, так як вона виглядає відмінною від інших секцій з перечисленням якихсб елементів. Хоча такий варіант теж не поганий.

2022-03-30 21:26 UTC, vitaliimak commented on src/yaroslav_hrytsiak/01/index.html
> +                <h4 class="title">Work Experience</h4>
Секції Projects, Experience, Education знаходяться на одному рівні і заголовок у них має бути одного рівня. `h3` в даному випадку.

2022-03-30 21:26 UTC, vitaliimak commented on src/yaroslav_hrytsiak/01/index.html
> +                </div>
Тут також можна продовжити використання `section`.

2022-03-30 21:26 UTC, vitaliimak commented on src/yaroslav_hrytsiak/02/index.html
> +                            <img src="images/source.PNG" alt="Google" title="Google" class="img1" >
На різних операційних системах діють різні правила щодо найменування файлів і папок. Тому те, що добре працює на Window не завжди буде працювати на Mac і Linux.
![2022-03-31_00-22](https://user-images.githubusercontent.com/6152066/160933218-2fd76a2b-13ea-4f30-8168-27b76bae6775.png)
Картинки не відобразилися тому, що на лінукс `source.png`, `Source.PNG`, and `source.PNG` три різних файла. Щоб запобігти цьому, варто іменувати файли і папки завжди в одному регістрі (в маленькому).

2022-03-30 21:26 UTC, vitaliimak commented on src/yaroslav_hrytsiak/02/index.html
> +<html lang="en">
Тут все ще англійська, хоча контент на українській.

2022-04-01 09:25 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/01/index.html
> +            </section>
Я тоді залишу такий варіантю

2022-04-01 09:26 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/01/index.html
> +                <h4 class="title">Work Experience</h4>
Done

2022-04-01 09:26 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/01/index.html
> +                </div>
Done

2022-04-01 09:26 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/02/index.html
> +                            <img src="images/source.PNG" alt="Google" title="Google" class="img1" >
Done

2022-04-01 09:26 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/02/index.html
> +<html lang="en">
Done

2022-04-02 15:39 UTC, vitaliimak submitted a review, later dismissed
Щоб додати перейменований файл у Windows у якого змінилася тільки регістер літер в індекс гіта потрібно виконати такі команді:
```bash
git mv Source.PNG source.png
# і далі стандартно
git add .
git commit
# ...
```
https://stackoverflow.com/questions/5551556/changing-file-names-in-a-git-repository

2022-04-02 15:56 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/01/index.html
> +                         <h3 class="work-position">Front-End Developer <span class="organization">Freelance</span>  </h3>
![errors](https://user-images.githubusercontent.com/95441431/161391009-62f4d8d8-9262-4f96-89bf-db44e24e3d95.PNG)
чомуст не хоче працювати команда git mv

2022-04-02 16:09 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/01/index.html
> +                         <h3 class="work-position">Front-End Developer <span class="organization">Freelance</span>  </h3>
Заголовки виправив.
Залишається відкрите питання перейменованих файлів у Windows

2022-04-02 16:29 UTC, YAroslav9405 commented on src/yaroslav_hrytsiak/01/index.html
> +                         <h3 class="work-position">Front-End Developer <span class="organization">Freelance</span>  </h3>
вирішив проблему з назвами картинок інакшим способом .
Будь ласка апрувни щерез реквест.

2022-04-02 17:39 UTC, vitaliimak commented on src/yaroslav_hrytsiak/01/index.html
> +                         <h3 class="work-position">Front-End Developer <span class="organization">Freelance</span>  </h3>
Хитро)

2022-04-02 17:40 UTC, vitaliimak approved these changes

2022-04-02 17:42 UTC, merged

2022-04-03 13:07 UTC, vitaliimak commented on src/yaroslav_hrytsiak/01/index.html
> +                         <h3 class="work-position">Front-End Developer <span class="organization">Freelance</span>  </h3>
> чомуст не хоче працювати команда git mv
Це тому, що файла Source.PNG вже немає в репозиторії. Щоб щось перейменувати це щось повинно існувати.

2022-04-03 13:35 UTC, vitaliimak commented on src/yaroslav_hrytsiak/01/index.html
> +                         <h3 class="work-position">Front-End Developer <span class="organization">Freelance</span>  </h3>
В принципі, `git mv` це не додавання файлу в індекс, а саме перейменування.